# Generated by Django 3.2.7 on 2021-10-17 11:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ScopeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('A', 'Fashion'), ('B', 'Portret'), ('C', 'Glamour'), ('D', 'Akt'), ('E', 'Edytorial'), ('F', 'Nagość zakryta'), ('G', 'Make up / stylizacja')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profession', models.CharField(choices=[('A', 'Modelka'), ('B', 'Model'), ('C', 'Fotograf'), ('D', 'Fryzjer'), ('E', 'Wizażysta'), ('F', 'Stylista'), ('G', 'Projektant'), ('H', 'Retuszer')], max_length=1)),
                ('experience', models.CharField(blank=True, choices=[('A', 'Niewielkie'), ('B', 'Średnie'), ('A', 'Duże')], max_length=1, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(260)])),
                ('bust', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(260)])),
                ('waistline', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(260)])),
                ('hips', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(260)])),
                ('hair', models.CharField(blank=True, choices=[('A', 'Krótkie'), ('B', 'Średnie'), ('C', 'Długie')], max_length=1, null=True)),
                ('eyes', models.CharField(blank=True, choices=[('A', 'Brązowe'), ('B', 'Ciemnobrązowe'), ('C', 'Piwne'), ('D', 'Bursztynowe'), ('E', 'Zielone'), ('F', 'Szare'), ('G', 'Niebieskie'), ('H', 'Fioletowe i czerwone')], max_length=1, null=True)),
                ('wear', models.CharField(blank=True, choices=[('A', 'XXS'), ('B', 'XS'), ('C', 'S'), ('D', 'M'), ('E', 'L'), ('F', 'XL'), ('G', 'XXL')], max_length=1, null=True)),
                ('shoes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(60)])),
                ('bra', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K')], max_length=1, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('visited', models.PositiveIntegerField(default=0)),
                ('profile_photo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_photo', to='photos.photo')),
                ('scope', models.ManyToManyField(blank=True, related_name='scopes', to='profiles.ScopeOfWork')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.region')),
            ],
        ),
    ]
