# Generated by Django 3.2.7 on 2021-10-17 11:49

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=photos.models.photo_directory_path)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('A', 'Fashion'), ('B', 'Portret'), ('C', 'Glamour')], max_length=1)),
                ('visited', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
