# Generated by Django 3.2.7 on 2021-10-28 08:18

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_height',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_width',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(height_field='photo_height', upload_to=photos.models.photo_directory_path, width_field='photo_width'),
        ),
    ]
