# Generated by Django 3.2.7 on 2021-10-28 08:19

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20211028_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo_height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photo_width',
            new_name='width',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(height_field='height', upload_to=photos.models.photo_directory_path, width_field='width'),
        ),
    ]
