# Generated by Django 3.2.7 on 2021-10-31 09:25

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_photo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='camera.png', height_field='height', upload_to=photos.models.photo_directory_path, width_field='width'),
        ),
    ]
